# Generated by Django 3.2.7 on 2022-01-05 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chairman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/images')),
                ('videofile', models.FileField(null=True, upload_to='media/videos', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/images')),
                ('videofile', models.FileField(null=True, upload_to='media/videos', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('duedate', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('penalty', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=30)),
                ('job_specification', models.CharField(max_length=50)),
                ('job_address', models.TextField(max_length=500)),
                ('birthdate', models.CharField(max_length=20)),
                ('no_of_members', models.CharField(max_length=50)),
                ('marrital_status', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('gender', models.CharField(default='male', max_length=20)),
                ('no_of_vehicles', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('id_proof', models.FileField(default='media/default.png', upload_to='media/documents')),
                ('profile_pic', models.FileField(default='media/default.png', upload_to='media/images')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.house')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/images')),
                ('videofile', models.FileField(null=True, upload_to='media/videos', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Chairman.user')),
                ('maintenance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MemberApp.maintenance')),
                ('member_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.notice')),
            ],
        ),
        migrations.CreateModel(
            name='LikeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.notice')),
            ],
        ),
        migrations.CreateModel(
            name='LikeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.event')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Family_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('mobileno', models.CharField(max_length=30)),
                ('job_specification', models.CharField(max_length=50)),
                ('job_address', models.TextField(max_length=500)),
                ('birthdate', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('relation', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(default='media/default.png', upload_to='media/images')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.event')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='EventLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.event')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MemberApp.member')),
            ],
        ),
    ]
